# Site
baseurl: ''
name: 'Diogo Matheus'
description: 'Description.'
favicon: 'assets/images/favicon.ico'
logo: 'assets/images/logo.png'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    diogomatheus:
      name: Diogo Matheus
      site: https://diogomatheus.github.io
      avatar: assets/images/diogomatheus-profile.jpg
      bio: "Software Engineer | Software Architect | Manager"
      email: dm.matheus@gmail.com
      twitter: https://twitter.com/diogomatheus_
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: diogomatheus
      avatar: assets/images/diogomatheus-profile.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]