# Site
baseurl: ''
permalink: /:categories/:year/:month/:day/:title:output_ext
favicon: 'assets/images/favicon.ico'
logo: 'assets/images/diogomatheus-logo.png'
name: 'Diogo Matheus'
description: 'Description.'
disqus: 'demowebsite'
include: ["_pages"]

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    diogomatheus:
      name: Diogo Matheus
      site: https://diogomatheus.github.io
      avatar: assets/images/diogomatheus-profile.jpg
      bio: "Software Engineer | Software Architect | Manager"
      email: dm.matheus@gmail.com
      twitter: https://twitter.com/diogomatheus_
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: diogomatheus
      avatar: assets/images/diogomatheus-profile.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]