# Website
baseurl: ''
name: Diogo Matheus
description: TO DO
favicon: assets/images/favicon.ico
logo: assets/images/diogomatheus-logo.png
permalink: /:year/:month/:day/:slug:output_ext
disqus: diogomatheus
include: [ _pages ]

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Authors
authors:
    diogomatheus:
      name: Diogo Matheus
      avatar: assets/images/diogomatheus-profile.jpg
      twitter: https://twitter.com/diogomatheus_
 
# Defaults
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: diogomatheus

# Pagination
paginate: 10
paginate_path: /page/:num/

# Exclude
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]